use_frameworks!

target 'MHPinterestLayout_Example' do
  pod 'MHPinterestLayout', :path => '../'
  pod 'SnapKit', '~> 3.2'
 
  
  
  target 'MHPinterestLayout_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
